image: Visual Studio 2017
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln
  parallel: true
